// Mocks generated by Mockito 5.4.6 from annotations
// in SafeNest/test/auth_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:SafeNest/core/models/auth_model.dart' as _i2;
import 'package:SafeNest/core/models/trusted_contact_model.dart' as _i4;
import 'package:SafeNest/core/models/user_model.dart' as _i3;
import 'package:SafeNest/core/repositories/auth_repository.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTokenResponse_0 extends _i1.SmartFake implements _i2.TokenResponse {
  _FakeTokenResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAnonymousSessionResponse_1 extends _i1.SmartFake
    implements _i2.AnonymousSessionResponse {
  _FakeAnonymousSessionResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_2 extends _i1.SmartFake implements _i3.User {
  _FakeUser_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTrustedContact_3 extends _i1.SmartFake
    implements _i4.TrustedContact {
  _FakeTrustedContact_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_4<T1> extends _i1.SmartFake implements _i5.Future<T1> {
  _FakeFuture_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i6.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<Map<String, dynamic>> requestOtp(
    String? phoneNumber, {
    String? countryCode = '+255',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #requestOtp,
              [phoneNumber],
              {#countryCode: countryCode},
            ),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<_i2.TokenResponse> verifyOtp(
    String? phoneNumber,
    String? otpCode, {
    String? countryCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #verifyOtp,
              [phoneNumber, otpCode],
              {#countryCode: countryCode},
            ),
            returnValue: _i5.Future<_i2.TokenResponse>.value(
              _FakeTokenResponse_0(
                this,
                Invocation.method(
                  #verifyOtp,
                  [phoneNumber, otpCode],
                  {#countryCode: countryCode},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.TokenResponse>);

  @override
  _i5.Future<_i2.AnonymousSessionResponse> createAnonymousSession({
    String? deviceFingerprint,
    String? languagePreference = 'en',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createAnonymousSession, [], {
              #deviceFingerprint: deviceFingerprint,
              #languagePreference: languagePreference,
            }),
            returnValue: _i5.Future<_i2.AnonymousSessionResponse>.value(
              _FakeAnonymousSessionResponse_1(
                this,
                Invocation.method(#createAnonymousSession, [], {
                  #deviceFingerprint: deviceFingerprint,
                  #languagePreference: languagePreference,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.AnonymousSessionResponse>);

  @override
  _i5.Future<_i2.TokenResponse> refreshAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshAccessToken, []),
            returnValue: _i5.Future<_i2.TokenResponse>.value(
              _FakeTokenResponse_0(
                this,
                Invocation.method(#refreshAccessToken, []),
              ),
            ),
          )
          as _i5.Future<_i2.TokenResponse>);

  @override
  _i5.Future<_i3.User> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i5.Future<_i3.User>.value(
              _FakeUser_2(this, Invocation.method(#getCurrentUser, [])),
            ),
          )
          as _i5.Future<_i3.User>);

  @override
  _i5.Future<_i3.User> updateProfile(_i3.UserProfileUpdate? update) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [update]),
            returnValue: _i5.Future<_i3.User>.value(
              _FakeUser_2(this, Invocation.method(#updateProfile, [update])),
            ),
          )
          as _i5.Future<_i3.User>);

  @override
  _i5.Future<List<_i4.TrustedContact>> getTrustedContacts() =>
      (super.noSuchMethod(
            Invocation.method(#getTrustedContacts, []),
            returnValue: _i5.Future<List<_i4.TrustedContact>>.value(
              <_i4.TrustedContact>[],
            ),
          )
          as _i5.Future<List<_i4.TrustedContact>>);

  @override
  _i5.Future<_i4.TrustedContact> addTrustedContact(
    _i4.TrustedContactCreate? contact,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addTrustedContact, [contact]),
            returnValue: _i5.Future<_i4.TrustedContact>.value(
              _FakeTrustedContact_3(
                this,
                Invocation.method(#addTrustedContact, [contact]),
              ),
            ),
          )
          as _i5.Future<_i4.TrustedContact>);

  @override
  _i5.Future<void> removeTrustedContact(String? contactId) =>
      (super.noSuchMethod(
            Invocation.method(#removeTrustedContact, [contactId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> clearStoredTokens() =>
      (super.noSuchMethod(
            Invocation.method(#clearStoredTokens, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<T> execute<T>(_i5.Future<T> Function()? apiCall) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [apiCall]),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#execute, [apiCall]),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_4<T>(this, Invocation.method(#execute, [apiCall])),
          )
          as _i5.Future<T>);

  @override
  _i5.Future<T> executeWithFallback<T>({
    required _i5.Future<T> Function()? apiCall,
    required _i5.Future<T> Function()? localFallback,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#executeWithFallback, [], {
              #apiCall: apiCall,
              #localFallback: localFallback,
            }),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#executeWithFallback, [], {
                      #apiCall: apiCall,
                      #localFallback: localFallback,
                    }),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_4<T>(
                  this,
                  Invocation.method(#executeWithFallback, [], {
                    #apiCall: apiCall,
                    #localFallback: localFallback,
                  }),
                ),
          )
          as _i5.Future<T>);
}
